config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [ :new, :create, :update ] do
    resources :answers, only: [ :new, :create ]
  end
  get "answers/load", to: "answers#load"
  root "pages#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to new_question_answer_path(@question.id), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_path, status: :see_other, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:mark_model, :km, :year, :problem, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
    <%= form_with(model: question, class: "space-y-6", data: { turbo: "false" }) do |form| %>
      <% if question.errors.any? %>
        <div id="error_explanation" class="bg-red-100 text-red-700 px-4 py-3 rounded-lg">
          <h2 class="font-bold"><%= pluralize(question.errors.count, "erro") %> impediram o salvamento:</h2>
          <ul class="list-disc list-inside mt-2">
            <% question.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <!-- Marca/Modelo -->
      <div>
        <%= form.label :mark_model, "Marca/Modelo", class: "block text-gray-700 font-medium" %>
        <%= form.text_field :mark_model, placeholder: "Ex.: Peugeot 208", class: "block w-full mt-2 px-4 py-2 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <!-- Quilometragem -->
      <div>
        <%= form.label :km, "Quilometragem", class: "block text-gray-700 font-medium" %>
        <%= form.text_field :km, placeholder: "Ex.: 50000", class: "block w-full mt-2 px-4 py-2 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <!-- Ano -->
      <div>
        <%= form.label :year, "Ano", class: "block text-gray-700 font-medium" %>
        <%= form.number_field :year, placeholder: "Ex.: 2020", class: "block w-full mt-2 px-4 py-2 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <!-- Problema -->
      <div>
        <%= form.label :problem, "Problema Identificado", class: "block text-gray-700 font-medium" %>
        <%= form.text_area :problem, placeholder: "Descreva o problema aqui...", rows: 4, class: "block w-full mt-2 px-4 py-2 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <!-- Botão de Enviar -->
      <div class="text-center">
        <%= form.submit "Enviar", class: "bg-blue-600 text-white py-3 px-6 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>
      </div>
    <% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Mark model:</strong>
    <%= question.mark_model %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Km:</strong>
    <%= question.km %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Year:</strong>
    <%= question.year %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Problem:</strong>
    <%= question.problem %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= question.user_id %>
  </p>

</div>

app/views/questions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing question</h1>

  <%= render "form", question: @question %>

  <%= link_to "Show this question", @question, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to questions", questions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/questions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Questions" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Questions</h1>
    <%= link_to "New question", new_question_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="questions" class="min-w-full">
    <% @questions.each do |question| %>
      <%= render question %>
      <p>
        <%= link_to "Show this question", question, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="min-h-screen bg-gray-100 flex items-center justify-center">
  <div class="w-full max-w-2xl bg-white shadow-lg rounded-lg p-6">
    <h1 class="text-2xl font-bold text-gray-800 mb-6 text-center">Informações do Veículo</h1>

  <%= render "form", question: @question %>

 
  </div>
</div>

app/views/questions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @question %>

    <%= link_to "Edit this question", edit_question_path(@question), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to questions", questions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this question", @question, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>